#!/usr/bin/env python3
"""
fetch_fonts.py — download latin/latin-ext woff2 subsets into assets/fonts/
and emit assets/fonts.css. Run once; the files are committed to the repo so
readers never hit a third-party server.
"""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "assets" / "fonts"
OUT.mkdir(parents=True, exist_ok=True)

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/120.0.0.0 Safari/537.36")

FAMILIES = {
    "Literata": "https://fonts.googleapis.com/css2?family=Literata:ital,opsz,wght@0,7..72,400;0,7..72,600;0,7..72,700;1,7..72,400;1,7..72,600&display=swap",
    "Inter": "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap",
    "JetBrains Mono": "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&display=swap",
}

KEEP = ("latin", "latin-ext")


def curl(url: str) -> bytes:
    return subprocess.run(["curl", "-sL", "--max-time", "60", "-A", UA, url],
                          capture_output=True, check=True).stdout


blocks: list[str] = []
count = 0

for family, css_url in FAMILIES.items():
    css = curl(css_url).decode()
    # each @font-face is preceded by a /* subset */ comment
    parts = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    for i in range(1, len(parts) - 1, 2):
        subset, block = parts[i], parts[i + 1]
        if subset not in KEEP:
            continue
        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        url = m.group(1)
        slug = family.lower().replace(" ", "-")
        weight = re.search(r"font-weight:\s*([^;]+);", block)
        style = re.search(r"font-style:\s*(\w+);", block)
        w = (weight.group(1).strip() if weight else "400").replace(" ", "-")
        s = style.group(1) if style else "normal"
        name = f"{slug}-{subset}-{w}-{s}.woff2"
        (OUT / name).write_bytes(curl(url))
        count += 1
        blocks.append(block.replace(url, f"fonts/{name}").strip())

(ROOT / "assets" / "fonts.css").write_text(
    "/* self-hosted subsets, generated by fetch_fonts.py -- do not edit */\n"
    + "\n".join(blocks) + "\n",
    encoding="utf-8",
)

total = sum(f.stat().st_size for f in OUT.glob("*.woff2"))
print(f"{count} files, {total/1024:.0f} KB -> {OUT}")
